name: Code Review com IA

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'app/Api/**'

jobs:
  code-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Executar Code Review com IA
        uses: seu-usuario/laravel-openai-code-review@v1.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
